--------------------------------------------------------
--  File created - «·Œ„Ì”-›»—«Ì—-09-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "ADMIN" 
   (	"ID" NUMBER(10,0), 
	"USERNAME" VARCHAR2(100 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BLOCK
--------------------------------------------------------

  CREATE TABLE "BLOCK" 
   (	"ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0), 
	"BLOCKER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "CATEGORY" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(100 CHAR), 
	"CREATOR" NUMBER(10,0), 
	"CREATORUNIQUE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORY_USERS
--------------------------------------------------------

  CREATE TABLE "CATEGORY_USERS" 
   (	"CATEGORY" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FRIENDS
--------------------------------------------------------

  CREATE TABLE "FRIENDS" 
   (	"ID" NUMBER(10,0), 
	"USER_1" NUMBER(10,0), 
	"USER_2" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GROUP
--------------------------------------------------------

  CREATE TABLE "GROUP" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(200 CHAR), 
	"CREATOR" NUMBER(10,0), 
	"CREATORUNIQUE" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table GROUP_USERS
--------------------------------------------------------

  CREATE TABLE "GROUP_USERS" 
   (	"GROUP_ID" NUMBER(10,0), 
	"USER_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NOTIFICATION
--------------------------------------------------------

  CREATE TABLE "NOTIFICATION" 
   (	"ID" NUMBER(10,0), 
	"DATERECIEVED" TIMESTAMP (6), 
	"CONTENT" VARCHAR2(100 CHAR), 
	"USER_ID" NUMBER(10,0), 
	"UNIQUEFIELD" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REQUEST
--------------------------------------------------------

  CREATE TABLE "REQUEST" 
   (	"ID" NUMBER(10,0), 
	"FROM_USER" NUMBER(10,0), 
	"TO_USER" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER
--------------------------------------------------------

  CREATE TABLE "USER" 
   (	"ID" NUMBER(10,0), 
	"FIRST_NAME" VARCHAR2(100 CHAR), 
	"LAST_NAME" VARCHAR2(100 CHAR), 
	"PASSWORD" VARCHAR2(100 CHAR), 
	"EMAIL" VARCHAR2(500 CHAR), 
	"GENDER" VARCHAR2(1 CHAR), 
	"MOBILE" NUMBER(11,0), 
	"BIRTHDATE" DATE, 
	"CITY" VARCHAR2(100 CHAR), 
	"COUNTRY" VARCHAR2(100 CHAR), 
	"BIO" VARCHAR2(200 CHAR), 
	"PIC_URL" VARCHAR2(500 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USER_STATE
--------------------------------------------------------

  CREATE TABLE "USER_STATE" 
   (	"USER_ID" NUMBER(10,0), 
	"ISOFFLINE" NUMBER(10,0), 
	"STATUS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence ADMIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence BLOCK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BLOCK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 27 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FRIEND_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FRIEND_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence GROUP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "GROUP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 32 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence NOTIFICATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTIFICATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence REQUEST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "REQUEST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 30 NOCACHE  NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence USER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "USER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 64 NOCACHE  NOORDER  NOCYCLE ;
REM INSERTING into ADMIN
SET DEFINE OFF;
Insert into ADMIN (ID,USERNAME,PASSWORD) values (5,'NAAA','naaa123');
REM INSERTING into BLOCK
SET DEFINE OFF;
REM INSERTING into CATEGORY
SET DEFINE OFF;
REM INSERTING into CATEGORY_USERS
SET DEFINE OFF;
REM INSERTING into FRIENDS
SET DEFINE OFF;
REM INSERTING into "GROUP"
SET DEFINE OFF;
REM INSERTING into GROUP_USERS
SET DEFINE OFF;
REM INSERTING into NOTIFICATION
SET DEFINE OFF;
REM INSERTING into REQUEST
SET DEFINE OFF;
REM INSERTING into "USER"
SET DEFINE OFF;
REM INSERTING into USER_STATE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index IDX_GROUP__CREATORUNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_GROUP__CREATORUNIQUE" ON "GROUP" ("CREATORUNIQUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_NOTIFICATION__UNIQUEFIELD
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_NOTIFICATION__UNIQUEFIELD" ON "NOTIFICATION" ("UNIQUEFIELD") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_CATEGORY__CREATOR
--------------------------------------------------------

  CREATE INDEX "IDX_CATEGORY__CREATOR" ON "CATEGORY" ("CREATOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FRIENDS_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "FRIENDS_UK1" ON "FRIENDS" ("USER_2", "USER_1") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_GROUP__CREATOR
--------------------------------------------------------

  CREATE INDEX "IDX_GROUP__CREATOR" ON "GROUP" ("CREATOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_GROUP_USER
--------------------------------------------------------

  CREATE INDEX "IDX_GROUP_USER" ON "GROUP_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_REQUEST
--------------------------------------------------------

  CREATE INDEX "IDX_REQUEST" ON "REQUEST" ("TO_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index REQUEST_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "REQUEST_UK1" ON "REQUEST" ("TO_USER", "FROM_USER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_FRIEND
--------------------------------------------------------

  CREATE INDEX "IDX_FRIEND" ON "FRIENDS" ("USER_2") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_CATEGORY_CREATORUNIQUE
--------------------------------------------------------

  CREATE UNIQUE INDEX "IDX_CATEGORY_CREATORUNIQUE" ON "CATEGORY" ("CREATORUNIQUE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USER_STATE_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "USER_STATE_UK1" ON "USER_STATE" ("USER_ID", "ISOFFLINE", "STATUS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_NOTIFICATION__USER
--------------------------------------------------------

  CREATE INDEX "IDX_NOTIFICATION__USER" ON "NOTIFICATION" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BLOCK_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "BLOCK_UK1" ON "BLOCK" ("BLOCKER", "USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN_PK" ON "ADMIN" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index IDX_CATEGORY_USER
--------------------------------------------------------

  CREATE INDEX "IDX_CATEGORY_USER" ON "CATEGORY_USERS" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMIN_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "ADMIN_UK1" ON "ADMIN" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger ADMIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "ADMIN_TRG" 
BEFORE INSERT ON ADMIN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID IS NULL THEN
      SELECT ADMIN_SEQ.NEXTVAL INTO :NEW.ID FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "ADMIN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger BLOCK_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "BLOCK_BI" 
  BEFORE INSERT ON "BLOCK"
  FOR EACH ROW
BEGIN
  IF :NEW."ID" IS NULL THEN
    SELECT "BLOCK_SEQ".NEXTVAL INTO :NEW."ID" FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "BLOCK_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORY_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CATEGORY_BI" 
  BEFORE INSERT ON "CATEGORY"
  FOR EACH ROW
BEGIN
  IF :NEW."ID" IS NULL THEN
    SELECT "CATEGORY_SEQ".NEXTVAL INTO :NEW."ID" FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "CATEGORY_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FRIEND_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "FRIEND_BI" 
  BEFORE INSERT ON "FRIENDS"
  FOR EACH ROW
BEGIN
  IF :NEW."ID" IS NULL THEN
    SELECT "FRIEND_SEQ".NEXTVAL INTO :NEW."ID" FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "FRIEND_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger GROUP_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GROUP_BI" 
  BEFORE INSERT ON "GROUP"
  FOR EACH ROW
BEGIN
  IF :NEW."ID" IS NULL THEN
    SELECT "GROUP_SEQ".NEXTVAL INTO :NEW."ID" FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "GROUP_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger NOTIFICATION_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "NOTIFICATION_BI" 
  BEFORE INSERT ON "NOTIFICATION"
  FOR EACH ROW
BEGIN
  IF :NEW."ID" IS NULL THEN
    SELECT "NOTIFICATION_SEQ".NEXTVAL INTO :NEW."ID" FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "NOTIFICATION_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger REQUEST_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "REQUEST_BI" 
  BEFORE INSERT ON "REQUEST"
  FOR EACH ROW
BEGIN
  IF :NEW."ID" IS NULL THEN
    SELECT "REQUEST_SEQ".NEXTVAL INTO :NEW."ID" FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "REQUEST_BI" ENABLE;
--------------------------------------------------------
--  DDL for Trigger USER_BI
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "USER_BI" 
  BEFORE INSERT ON "USER"
  FOR EACH ROW
BEGIN
  IF :NEW."ID" IS NULL THEN
    SELECT "USER_SEQ".NEXTVAL INTO :NEW."ID" FROM DUAL;
  END IF;
END;

/
ALTER TRIGGER "USER_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table GROUP
--------------------------------------------------------

  ALTER TABLE "GROUP" MODIFY ("CREATORUNIQUE" NOT NULL ENABLE);
  ALTER TABLE "GROUP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "GROUP" MODIFY ("CREATOR" NOT NULL ENABLE);
  ALTER TABLE "GROUP" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "ADMIN" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "ADMIN" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN" ADD CONSTRAINT "ADMIN_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN" ADD CONSTRAINT "ADMIN_UK1" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE "REQUEST" ADD CONSTRAINT "REQUEST_UK1" UNIQUE ("TO_USER", "FROM_USER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "REQUEST" MODIFY ("FROM_USER" NOT NULL ENABLE);
  ALTER TABLE "REQUEST" MODIFY ("TO_USER" NOT NULL ENABLE);
  ALTER TABLE "REQUEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GROUP_USERS
--------------------------------------------------------

  ALTER TABLE "GROUP_USERS" MODIFY ("GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "GROUP_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "GROUP_USERS" ADD PRIMARY KEY ("GROUP_ID", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FRIENDS
--------------------------------------------------------

  ALTER TABLE "FRIENDS" MODIFY ("USER_1" NOT NULL ENABLE);
  ALTER TABLE "FRIENDS" MODIFY ("USER_2" NOT NULL ENABLE);
  ALTER TABLE "FRIENDS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FRIENDS" ADD CONSTRAINT "FRIENDS_UK1" UNIQUE ("USER_2", "USER_1")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER
--------------------------------------------------------

  ALTER TABLE "USER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "USER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "USER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "USER" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "USER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "USER" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORY_USERS
--------------------------------------------------------

  ALTER TABLE "CATEGORY_USERS" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "CATEGORY_USERS" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "CATEGORY_USERS" ADD PRIMARY KEY ("CATEGORY", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BLOCK
--------------------------------------------------------

  ALTER TABLE "BLOCK" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "BLOCK" MODIFY ("BLOCKER" NOT NULL ENABLE);
  ALTER TABLE "BLOCK" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BLOCK" ADD CONSTRAINT "BLOCK_UK1" UNIQUE ("BLOCKER", "USER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USER_STATE
--------------------------------------------------------

  ALTER TABLE "USER_STATE" MODIFY ("ISOFFLINE" NOT NULL ENABLE);
  ALTER TABLE "USER_STATE" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "USER_STATE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "USER_STATE" ADD CONSTRAINT "USER_STATE_UK1" UNIQUE ("USER_ID", "ISOFFLINE", "STATUS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "NOTIFICATION" MODIFY ("UNIQUEFIELD" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICATION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "NOTIFICATION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "CATEGORY" MODIFY ("CREATORUNIQUE" NOT NULL ENABLE);
  ALTER TABLE "CATEGORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "CATEGORY" MODIFY ("CREATOR" NOT NULL ENABLE);
  ALTER TABLE "CATEGORY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BLOCK
--------------------------------------------------------

  ALTER TABLE "BLOCK" ADD CONSTRAINT "FK_BLOCK__BLOCKER" FOREIGN KEY ("BLOCKER")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "BLOCK" ADD CONSTRAINT "FK_BLOCK__USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "CATEGORY" ADD CONSTRAINT "FK_CATEGORY__CREATOR" FOREIGN KEY ("CREATOR")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CATEGORY_USERS
--------------------------------------------------------

  ALTER TABLE "CATEGORY_USERS" ADD CONSTRAINT "FK_CATEGORY_USERS__CATEGORY" FOREIGN KEY ("CATEGORY")
	  REFERENCES "CATEGORY" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "CATEGORY_USERS" ADD CONSTRAINT "FK_CATEGORY_USERS__USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FRIENDS
--------------------------------------------------------

  ALTER TABLE "FRIENDS" ADD CONSTRAINT "FK_FRIEND__USER" FOREIGN KEY ("USER_1")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "FRIENDS" ADD CONSTRAINT "FK_FRIEND__USER_2" FOREIGN KEY ("USER_2")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUP
--------------------------------------------------------

  ALTER TABLE "GROUP" ADD CONSTRAINT "FK_GROUP__CREATOR" FOREIGN KEY ("CREATOR")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table GROUP_USERS
--------------------------------------------------------

  ALTER TABLE "GROUP_USERS" ADD CONSTRAINT "FK_GROUP_USER__GROUP" FOREIGN KEY ("GROUP_ID")
	  REFERENCES "GROUP" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "GROUP_USERS" ADD CONSTRAINT "FK_GROUP_USER__USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATION
--------------------------------------------------------

  ALTER TABLE "NOTIFICATION" ADD CONSTRAINT "FK_NOTIFICATION__USER" FOREIGN KEY ("USER_ID")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REQUEST
--------------------------------------------------------

  ALTER TABLE "REQUEST" ADD CONSTRAINT "FK_REQUEST__FROM_USER" FOREIGN KEY ("FROM_USER")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
  ALTER TABLE "REQUEST" ADD CONSTRAINT "FK_REQUEST__TO_USER" FOREIGN KEY ("TO_USER")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table USER_STATE
--------------------------------------------------------

  ALTER TABLE "USER_STATE" ADD CONSTRAINT "USER_STATE_FK1" FOREIGN KEY ("USER_ID")
	  REFERENCES "USER" ("ID") ON DELETE CASCADE ENABLE;
